debug: false
root: /
exitpage: /
db:
  prefix: postgresql+psycopg2://
  name: {{DBNAME}}
  user: {{DBUSER}}
  password: {{DBPASSWORD}}
  host: {{DBHOST}}
  port: null
  table_prefix: null
oauth:
  facebook:
    enable: false
    id: 423759825983740
    secret: 34993a09909c0909b9000a090d09f099
  google:
    enable: false
    id: 23123018240-32239fj28fj4fuhf394h3984eurhfurh.apps.googleusercontent.com
    secret: DGE34gdgerg3GDG545tgdfRf
secretkey: 28asflwjeifwlfjsd2fejfiefw3g4o87
appname: docassemble
brandname: demo
packagecache: /tmp/docassemble-cache
uploads: /usr/share/docassemble/files
packages: /usr/share/docassemble/local
webapp: /usr/share/docassemble/webapp/docassemble.wsgi
mail:
  username: null
  password: null
  server: localhost
  port: 25
  use_ssl: false
  use_tls: false
  default_sender: '"Administrator" <no-reply@example.com>'
admin_address: '"Administrator" <admin@example.com>'
use_progress_bar: false
imagemagick: convert
pdftoppm: pdftoppm
pacpl: pacpl
avconv: avconv
default_interview: docassemble.demo:data/questions/questions.yml
flask_log: /tmp/flask.log
language: en
locale: US.utf8
default_admin_account:
  nickname: admin
  email: admin@admin.com
  password: password
voicerss:
  enable: false
  key: ae8734983948ebc98239e9898f998432
  languages:
    en: us
    es: mx
    fr: fr
s3:
  enable: {{S3ENABLE}}
  access_key_id: {{S3ACCESSKEY}}
  secret_access_key: {{S3SECRETACCESSKEY}}
  bucket: {{S3BUCKET}}