debug: false
root: /demo
exitpage: /
db:
  prefix: postgresql+psycopg2://
  name: docassemble
  user: null
  password: null
  host: null
  port: null
oauth:
  facebook:
    id: 423759825983740
    secret: 34993a09909c0909b9000a090d09f099
  google:
    id: 23123018240-32239fj28fj4fuhf394h3984eurhfurh.apps.googleusercontent.com
    secret: DGE34gdgerg3GDG545tgdfRf
secretkey: 28asflwjeifwlfjsd2fejfiefw3g4o87
appname: docassemble
brandname: demo
uploads: /usr/share/docassemble/files
mail:
  default_sender: '"Administrator" <no-reply@example.com>'
admin_address: '"Administrator" <admin@example.com>'