# name: Build and Push to GCR
# on: [push]

# jobs:
#   # This job uses Buildx layer caching
#   fake_deploy_cache_single:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2

#       - name: Prepare
#         id: prep
#         run: |
#           TAG=$(echo $GITHUB_SHA | head -c7)
#           IMAGE="ghcr.io/jheyer159/docassemble"
#           echo ::set-output name=tagged_image::${IMAGE}:${TAG}
#           echo ::set-output name=tag::${TAG}
#       - name: Set up Docker Buildx
#         id: buildx
#         uses: docker/setup-buildx-action@master

#       # Registry login step intentionally missing
#       - name: Login to GitHub Container Registry
#         uses: docker/login-action@v1
#         with:
#           registry: ghcr.io
#           username: ${{ github.actor }}
#           password: ${{ secrets.GITHUB_TOKEN }}

#       - name: Cache Docker layers
#         uses: actions/cache@v2
#         with:
#           path: /tmp/.buildx-cache
#           key: ${{ runner.os }}-single-buildx-${{ github.sha }}
#           restore-keys: |
#             ${{ runner.os }}-single-buildx

#       - name: Build production image
#         uses: docker/build-push-action@v2
#         with:
#           context: .
#           builder: ${{ steps.buildx.outputs.name }}
#           file: Dockerfile
#           push: true # This would be set to true in a real world deployment scenario.
#           tags: ${{ steps.prep.outputs.tagged_image }}
#           cache-from: type=local,src=/tmp/.buildx-cache
#           cache-to: type=local,dest=/tmp/.buildx-cache-new

#       - name: Move cache
#         run: |
#           rm -rf /tmp/.buildx-cache
#           mv /tmp/.buildx-cache-new /tmp/.buildx-cache
